---
title: "Test GitHub Actions With R"
author: Al JalalAbadi^[Melbourne Integrative Genomics, The University of Melbourne (al.jal.abadi@gmail.com)]
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Test GitHub Actions With R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Load the required packages:

```{r}
library(ggplot2)
ggplot(mpg, aes(class)) + geom_bar()
```

```{r, echo=TRUE}
library(MOFA2)
mofapy2_av <- reticulate::py_module_available('mofapy2')
if (!mofapy2_av) {
  cat('mofapy2 unavailable ... \n ')
  
  cat('python being used:\n')
  cat(system('which python', intern = TRUE))
  py_conf <- unclass(reticulate::py_config()) 
  cat('\nrequired_module_path: \n')
  message(py_conf$required_module_path)

  all_pys <- unclass(reticulate::py_config())$python_versions
  cat('\n\nPythons:\n')
  message(paste(all_pys, collapse = '\n'))
  
  for (py in all_pys) {
    message('using python: ', py, ':\n')
    reticulate::use_python(py)
    av <- reticulate::py_module_available('mofapy2')
    if (av) {
      cat('Available!\n')
    } else {
      cat('Unavailable\n')
    }
  }
}
```
